services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Behat\bootstrap\FeatureContext:
        public: true
        autowire: true
        autoconfigure: true
        arguments:
            - "@kernel"
